[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
bitvec = "1.0.1"
im = "15.1.0"
itertools = "0.10.5"
peg = "0.8.1"
thiserror = "1.0.37"
