[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advtools = { version = "0.8.0", path = "../advtools" }
cargo-fixeq = "0.4.0"
